### PR TITLE
Added enum to int conversion for unmapped side of binary expressions

### LINKED ISSUE #162: Consider conversions between Integers and Enums
### Discussed in https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/discussions/161

<div type='discussions-op-text'>

<sup>Originally posted by **ErikGjers** February  9, 2023</sup>
Hi,

I am having an issue with the library. I am using it to translate expressions regarding filtering in a database query. Below I have code to illustrate a simple example that causes the issue.
```
internal enum Color
{
	red = 1,
	green = 2,
	blue = 3
}
```
```
internal class Car
{
	public Color Trim { get; set; }
}
```
```
internal class DbCar
{
	public int Trim { get; set; }
}
```
```
internal class CarMap : Profile
{
	public CarMap()
	{
		CreateMap<Car, DbCar>().ReverseMap();
	}
}
```
```
internal static Expression<Func<DbCar, bool>> TranslateCar()
{
	//Build the expression to translate
	var param = Expression.Parameter(typeof(Car), "c");
	var paramWithProp = Expression.Property(param, nameof(Car.Trim));
	var constant = Expression.Constant(Color.green, typeof(Color));
	var ex = Expression.NotEqual(paramWithProp, constant);
	var exLambda = Expression.Lambda(ex, param);
	//Expression is now {c => c.Trim != Color.green}

	var mapper = new MapperConfiguration(config => config.AddProfile(new CarMap())).CreateMapper();

	var translatedEx = mapper.MapExpression<Expression<Func<DbCar, bool>>>(exLambda);
	return translatedEx;
}
```

Calling TranslateCar causes an exception:

System.InvalidOperationException: 'The binary operator NotEqual is not defined for the types 'System.Int32' and 'Test+Color'.'

This seems to me that the constant part of the expression is not being translated, but the other side of the expression is. I tried a few different ways of mapping the attribute with a custom resolver, but nothing seems to affect the constant part of the expression.

One way to fix it is to not have it map from an enum to an int, but I would certainly like to have that as an option for when appropriate.

Is this the intended effect? If it is, how do I go about fixing this issue? Thanks for any help.</div>

### PR DESCRIPTION
**Pull request by ErikGjers**
Fixes #162 

Was not able to do anything that would fix the issue at the ConstantExpression part of the visitor that was pointed out, but instead edited the BinaryExpression visiting part to have a conversion expression added.

Feedback appreciated.

### CODE REVIEW

**Comment by ErikGjers** [comment]
The changes I made to the PR cover the requirements I believe. What you had written worked. Just dropping a message here in case the change went unnoticed. Feedback is always appreciated.

**Comment by ErikGjers** [comment]
I'll add some tests and potential changes in the next couple of days.

**Comment by ErikGjers** [comment]
I tried to include some string -> enum and enum -> string conversions, but these were failing. Since they weren't specifically part of this issue, though I figured it would be nice to have, I removed them for the time being.

Should I expand further on these tests, or do they cover the needs for the feature?

Sorry for the delay, travel and work got in the way.

**Comment by BlaiseD** [comment]
No hurry  - correct that string conversions don't apply here.

**Pull request merged**
